apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-backend
  template:
    metadata:
      labels:
        app: chat-app-backend
    spec:
      containers:
        - name: backend
          image: marckostar7321/chat-app-backend:v1
          ports:
            - containerPort: 4002
          envFrom:
            - secretRef:
                name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend
spec:
  selector:
    app: chat-app-backend
  ports:
    - protocol: TCP
      port: 4002         # The service port within the cluster
      targetPort: 4002   # The port on which the backend container is listening
  type: ClusterIP
