version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    env_file:
      - Backend/.env
    ports:
      - "4002:4002"
    networks:
      - chat-app-network

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "3001:80"
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge
