version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/AKChat
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:4002

volumes:
  mongodb_data:
    driver: local
